# Site settings
title: Chris Bamborough
email: bamborough.c@gmail.com
description: The personal website of Chris Bamborough
about: |
  Chris Bamborough is a designer and researcher working in the field of architecture. His practice concentrates on the effects of networked communication technology on the built environment. His approach is to utilise the tools of multiple disciplines to produce novel methods for exploring the performance of the built environment.
mc_about: |
  Making Culture is a collection of thoughts and reflections related to Chris Bamborough's PHD research into digital culture and infrastructures in Architecture.

  The Making Culture project was inititated by a research travel scholarship awarded from the The Byera Hadley Travelling Fund in 2014. This enabled visits to spaces of community making in Australia and the US to study and understand the potential benefits of personal fabrication for architecture and vice versa. It was interested in how community making could potentially provide a vehicle for architects to better connect the esoteric nature of architectural design and increase public appreciation of architecture.

  The project has evolved since to explore how architecture can adapt to remain relevant in todays digitally networked society, while helping to reconnect digital culture and design with the material and tectonic traditions of architecture.

bhts_about: An study of maker communities and their associated spaces in Boston, San Fransisco, Adelaide and Sydney.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chrisbamborough.com" # the base hostname & protocol for your site
twitter_username: chrisbamborough
github_username: chrisbamborough
behance_username: chrisbamborough
medium_username: "@chrisbamborough"
soundcloud_username: smoothspace
vimeo_username: chrisbamborough
# googleplus_username: +chrisbamborough
# instagram_username: chrisbamborough
# flickr_username: chrisbamborough
# linkedin_username: chrisbamborough
pinterest_uername: chrisbamborough

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 4
author: Chris Bamborough
plugins: [jekyll-paginate]
